name: aitraf
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=1.13.1
  - torchvision=0.14.1
  - torchaudio=0.13.1
  - pytorch-cuda=11.7
  - numpy<2
  - pandas
  - scikit-learn
  - scikit-image
  - matplotlib
  - jupyter
  - opencv
  - tqdm
  - seaborn
  - tensorboard
  - moviepy
  - albumentations
  - notebook
  - gxx_linux-64=11
  - gcc_linux-64=11
  - make
  - pip
  - pip:
      - openpifpaf==0.13.11
